"""initial_baseline_schema

Revision ID: 5cbba4aa58e3
Revises: 
Create Date: 2026-09-14 12:46:06.742197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types


# revision identifiers, used by Alembic.
revision: str = '5cbba4aa58e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChatMessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('avatarColor', sa.String(), nullable=False),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('track', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('totalRaces', sa.Integer(), nullable=False),
    sa.Column('currentRace', sa.Integer(), nullable=False),
    sa.Column('date', app.types.PrismaDateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('passwordHash', sa.String(), nullable=True),
    sa.Column('isGuest', sa.Boolean(), nullable=False),
    sa.Column('guestToken', sa.String(), nullable=True),
    sa.Column('avatarColor', sa.String(), nullable=False),
    sa.Column('gameMode', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('birthYear', sa.Integer(), nullable=True),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.Column('updatedAt', app.types.PrismaDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('guestToken'),
    sa.UniqueConstraint('username')
    )
    op.create_table('AchievementCard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('cardId', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('earnedAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'cardId')
    )
    op.create_table('Group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('founderId', sa.Integer(), nullable=False),
    sa.Column('privacyMode', sa.Boolean(), nullable=False),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['founderId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LeaderboardEntry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('tournamentId', sa.Integer(), nullable=False),
    sa.Column('ticketNumber', sa.Integer(), nullable=False),
    sa.Column('totalPoints', sa.Integer(), nullable=False),
    sa.Column('racesPlayed', sa.Integer(), nullable=False),
    sa.Column('fullPoints', sa.Integer(), nullable=False),
    sa.Column('dualPoints', sa.Integer(), nullable=False),
    sa.Column('smartPoints', sa.Integer(), nullable=False),
    sa.Column('winStreak', sa.Integer(), nullable=False),
    sa.Column('bestStreak', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('previousRank', sa.Integer(), nullable=True),
    sa.Column('rankChange', sa.Integer(), nullable=False),
    sa.Column('lastPointsChange', sa.Integer(), nullable=False),
    sa.Column('originalCreatorAlias', sa.String(), nullable=True),
    sa.Column('isClaimed', sa.Boolean(), nullable=False),
    sa.Column('claimedByUserId', sa.Integer(), nullable=True),
    sa.Column('updatedAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournamentId'], ['Tournament.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'tournamentId', 'ticketNumber')
    )
    op.create_table('Race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournamentId', sa.Integer(), nullable=False),
    sa.Column('raceNumber', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduledTime', sa.String(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('raceClass', sa.String(), nullable=True),
    sa.Column('purse', sa.Integer(), nullable=True),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournamentId'], ['Tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournamentId', 'raceNumber')
    )
    op.create_table('UserStats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('totalPoints', sa.Integer(), nullable=False),
    sa.Column('tournamentsPlayed', sa.Integer(), nullable=False),
    sa.Column('totalRaces', sa.Integer(), nullable=False),
    sa.Column('winRate', sa.Float(), nullable=False),
    sa.Column('bestStreak', sa.Integer(), nullable=False),
    sa.Column('titles', sa.Integer(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('updatedAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('GroupHologram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupId', sa.Integer(), nullable=False),
    sa.Column('authorId', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('colorVersion', sa.String(), nullable=False),
    sa.Column('sentAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['User.id'], ),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GroupHologramCooldown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupId', sa.Integer(), nullable=False),
    sa.Column('nextAvailableAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupId'),
    sa.UniqueConstraint('groupId')
    )
    op.create_table('GroupMember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requestedAt', app.types.PrismaDateTime(), nullable=True),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupId', 'userId')
    )
    op.create_table('Horse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=False),
    sa.Column('postPosition', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('jockey', sa.String(), nullable=True),
    sa.Column('trainer', sa.String(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('scratched', sa.Boolean(), nullable=False),
    sa.Column('silkPrimary', sa.String(), nullable=True),
    sa.Column('silkSecondary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['raceId'], ['Race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=False),
    sa.Column('tournamentId', sa.Integer(), nullable=False),
    sa.Column('ticketNumber', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('picks', sa.String(), nullable=False),
    sa.Column('pointsEarned', sa.Integer(), nullable=False),
    sa.Column('isScored', sa.Boolean(), nullable=False),
    sa.Column('originalCreatorAlias', sa.String(), nullable=True),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raceId'], ['Race.id'], ),
    sa.ForeignKeyConstraint(['tournamentId'], ['Tournament.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'raceId', 'ticketNumber')
    )
    op.create_table('RaceResult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=False),
    sa.Column('horseId', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horseId'], ['Horse.id'], ),
    sa.ForeignKeyConstraint(['raceId'], ['Race.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raceId', 'horseId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RaceResult')
    op.drop_table('Ticket')
    op.drop_table('Horse')
    op.drop_table('GroupMember')
    op.drop_table('GroupHologramCooldown')
    op.drop_table('GroupHologram')
    op.drop_table('UserStats')
    op.drop_table('Race')
    op.drop_table('LeaderboardEntry')
    op.drop_table('Group')
    op.drop_table('AchievementCard')
    op.drop_table('User')
    op.drop_table('Tournament')
    op.drop_table('ChatMessage')
    # ### end Alembic commands ###
