"""domain_identity_dividends_tickets

Revision ID: 64620c348393
Revises: 5cbba4aa58e3
Create Date: 2026-09-19 07:29:27.641959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types


# revision identifiers, used by Alembic.
revision: str = '64620c348393'
down_revision: Union[str, Sequence[str], None] = '5cbba4aa58e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TournamentTicket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('tournamentId', sa.Integer(), nullable=False),
    sa.Column('ticketNumber', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('isAdUnlocked', sa.Boolean(), nullable=False),
    sa.Column('adUnlockToken', sa.String(), nullable=True),
    sa.Column('totalPoints', sa.Integer(), nullable=False),
    sa.Column('originalCreatorAlias', sa.String(), nullable=True),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.Column('updatedAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournamentId'], ['Tournament.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'tournamentId', 'ticketNumber')
    )
    op.create_table('TicketSelection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournamentTicketId', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=False),
    sa.Column('raceOrder', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('picks', sa.String(), nullable=False),
    sa.Column('pointsEarned', sa.Integer(), nullable=False),
    sa.Column('isScored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['raceId'], ['Race.id'], ),
    sa.ForeignKeyConstraint(['tournamentTicketId'], ['TournamentTicket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournamentTicketId', 'raceId')
    )
    op.create_table('TournamentRankSnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournamentId', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=False),
    sa.Column('raceNumber', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('ticketNumber', sa.Integer(), nullable=False),
    sa.Column('pointsAtRace', sa.Integer(), nullable=False),
    sa.Column('rankAtRace', sa.Integer(), nullable=False),
    sa.Column('pointsBehindLeader', sa.Integer(), nullable=False),
    sa.Column('pointsBehindNext', sa.Integer(), nullable=False),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raceId'], ['Race.id'], ),
    sa.ForeignKeyConstraint(['tournamentId'], ['Tournament.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournamentId', 'raceId', 'userId', 'ticketNumber')
    )
    op.create_table('OfficialDividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=False),
    sa.Column('horseId', sa.Integer(), nullable=False),
    sa.Column('winPayoff', sa.Float(), nullable=False),
    sa.Column('dividend', sa.Float(), nullable=False),
    sa.Column('isDeadHeat', sa.Boolean(), nullable=False),
    sa.Column('createdAt', app.types.PrismaDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horseId'], ['Horse.id'], ),
    sa.ForeignKeyConstraint(['raceId'], ['Race.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raceId', 'horseId')
    )
    with op.batch_alter_table('Horse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendorRunnerId', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('programNumber', sa.String(), nullable=True))

    with op.batch_alter_table('LeaderboardEntry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pointsBehindNext', sa.Integer(), nullable=False))

    with op.batch_alter_table('Race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendorRaceId', sa.String(), nullable=True))

    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendorMeetId', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tournament', schema=None) as batch_op:
        batch_op.drop_column('vendorMeetId')

    with op.batch_alter_table('Race', schema=None) as batch_op:
        batch_op.drop_column('vendorRaceId')

    with op.batch_alter_table('LeaderboardEntry', schema=None) as batch_op:
        batch_op.drop_column('pointsBehindNext')

    with op.batch_alter_table('Horse', schema=None) as batch_op:
        batch_op.drop_column('programNumber')
        batch_op.drop_column('vendorRunnerId')

    op.drop_table('OfficialDividend')
    op.drop_table('TournamentRankSnapshot')
    op.drop_table('TicketSelection')
    op.drop_table('TournamentTicket')
    # ### end Alembic commands ###
